services:
  mysql-backend:
    container_name: workspace-backend
    image: mysql:8.0.42-debian
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./workspace-backend:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - 3333:3306
    healthcheck:
      test: ["CMD-SHELL", "mysql -h localhost -u ${MYSQL_USER} -p ${MYSQL_PASSWORD} -e 'SELECT 1' ${MYSQL_DATABASE}"]
      interval: 10s
      retries: 5

      start_period: 30s
